name: myBinder-environment

dependencies:
  - python=3.6
  - biopython=1.70
  - mmtf-python=1.1.2
  - pyarrow=0.9.0
  - numpy=1.14.5
  - requests=2.19.1
  - sympy=1.1.1
  - matplotlib=2.2.2
  - nose
  - ipywidgets=7.2.1
  - seaborn=0.8.1
  - pyspark=2.3.1
  - py4j=0.10.7
  - python-dateutil
  - pip:
      - mmtfPyspark==0.2.6
      - py3Dmol==0.7.2
